/**
 * Optimal play, solved exactly.
 *
 * "Should I burn a re-roll on this?" is the only real decision in Gussle, and
 * it has a correct answer. The game is a small Markov decision process, so we
 * can solve it rather than guess at it:
 *
 *   state  = (digits left, re-rolls left, bullseyes so far,
 *             total distance so far, worst distance so far)
 *   action = keep the digit, or spend a re-roll on it
 *
 * That's 110,400 states, which is nothing. The solved table is used for two
 * things: the percentile table is generated by simulating *this* policy, so
 * "top 5%" means "better than 95% of optimally-played days" rather than
 * "better than 95% of some arbitrary reference player"; and the UI can offer
 * it as an optional coach.
 *
 * One documented simplification: the DP does not look ahead to the consecutive
 * "Bullseye Run" bonus, which would need the current run length in the state
 * and multiply its size by ~100 for a bonus that is rare and small relative to
 * the combo it already models. Runs are treated as a windfall.
 */

import {
  ROLL_LENGTH,
  REROLLS_PER_DAY,
  DIGIT_POINTS,
  BULLSEYE_BONUS,
  UNUSED_REROLL_BONUS,
  DISTANCE_WEIGHTS,
  distance,
} from './scoring.js';

const MAX_TOTAL = ROLL_LENGTH * 5;
const R = REROLLS_PER_DAY + 1;
const B = ROLL_LENGTH + 1;
const T = MAX_TOTAL + 1;
const W = 6;

const index = (i, r, b, t, w) => ((((i * R + r) * B + b) * T + t) * W + w);
const SIZE = (ROLL_LENGTH + 1) * R * B * T * W;

/** Bonuses that can only be settled once every digit is resolved. */
function terminalBonus(bullseyes, total, worst, rerollsLeft) {
  let bonus = BULLSEYE_BONUS[bullseyes] || 0;
  if (total <= 12) bonus += Math.round(150 * Math.pow(1.6, 12 - total));
  if (worst <= 2) bonus += Math.round(1200 * Math.pow(3, 2 - worst));
  bonus += rerollsLeft * UNUSED_REROLL_BONUS;
  // Every digit maximally wrong is only possible at total distance 45.
  if (total === MAX_TOTAL) bonus += 1000000;
  return bonus;
}

let table = null;

/** Solves the MDP once and caches it. Values are expected final scores. */
export function solve() {
  if (table) return table;
  const V = new Float64Array(SIZE);

  // i = 0: nothing left to roll, so the value is just the end-of-day bonuses.
  for (let r = 0; r < R; r++) {
    for (let b = 0; b < B; b++) {
      for (let t = 0; t < T; t++) {
        for (let w = 0; w < W; w++) {
          V[index(0, r, b, t, w)] = terminalBonus(b, t, w, r);
        }
      }
    }
  }

  // Re-rolls are resolved in increasing order of r, because spending one moves
  // to the same digit count with r-1 — a value we must already know.
  for (let i = 1; i <= ROLL_LENGTH; i++) {
    for (let r = 0; r < R; r++) {
      for (let b = 0; b < B; b++) {
        for (let t = 0; t < T; t++) {
          for (let w = 0; w < W; w++) {
            const rerollValue = r > 0 ? V[index(i, r - 1, b, t, w)] : -Infinity;

            let expected = 0;
            for (let d = 0; d < W; d++) {
              const keep =
                DIGIT_POINTS[d] +
                V[index(i - 1, r, Math.min(b + (d === 0 ? 1 : 0), B - 1), Math.min(t + d, T - 1), Math.max(w, d))];
              expected += DISTANCE_WEIGHTS[d] * Math.max(keep, rerollValue);
            }
            V[index(i, r, b, t, w)] = expected;
          }
        }
      }
    }
  }

  table = V;
  return V;
}

/**
 * Should this digit be re-rolled?
 *
 * `progress` describes the state *before* the current digit is settled:
 * how many digits (including this one) are still unresolved, re-rolls left, and
 * the tallies so far.
 */
export function shouldReroll(rolledDistance, { digitsLeft, rerollsLeft, bullseyes, total, worst }) {
  if (rerollsLeft <= 0) return false;
  const V = solve();

  const b = Math.min(bullseyes, B - 1);
  const t = Math.min(total, T - 1);
  const keep =
    DIGIT_POINTS[rolledDistance] +
    V[
      index(
        digitsLeft - 1,
        rerollsLeft,
        Math.min(b + (rolledDistance === 0 ? 1 : 0), B - 1),
        Math.min(t + rolledDistance, T - 1),
        Math.max(worst, rolledDistance),
      )
    ];
  const reroll = V[index(digitsLeft, rerollsLeft - 1, b, t, worst)];
  return reroll > keep;
}

/** Expected final score from a state, for the "what's this worth?" readout. */
export function expectedScore({ digitsLeft, rerollsLeft, bullseyes, total, worst }) {
  const V = solve();
  return V[
    index(
      digitsLeft,
      rerollsLeft,
      Math.min(bullseyes, B - 1),
      Math.min(total, T - 1),
      Math.min(worst, W - 1),
    )
  ];
}

/**
 * Plays one full day under the optimal policy. Used to generate the percentile
 * table, and as the yardstick the game is ranked against.
 */
export function playOptimally(target, rand) {
  const rolled = new Array(ROLL_LENGTH);
  let rerollsLeft = REROLLS_PER_DAY;
  let bullseyes = 0;
  let total = 0;
  let worst = 0;

  for (let i = 0; i < ROLL_LENGTH; i++) {
    const digitsLeft = ROLL_LENGTH - i;
    let digit = Math.floor(rand() * 10);
    let d = distance(target[i], digit);

    while (
      rerollsLeft > 0 &&
      shouldReroll(d, { digitsLeft, rerollsLeft, bullseyes, total, worst })
    ) {
      rerollsLeft--;
      digit = Math.floor(rand() * 10);
      d = distance(target[i], digit);
    }

    rolled[i] = digit;
    if (d === 0) bullseyes++;
    total += d;
    worst = Math.max(worst, d);
  }

  return { rolled, rerollsLeft };
}
